[package]
name = "growatt_server"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.188"
serde_yaml = "0.9.25"
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
tokio-util = "0.7.8"
futures = "0.3.28"
bytes = "1.5.0"