version: "3.9"
services:
  timescale:
    container_name: postgres
    image: timescale/timescaledb-ha:pg15.3-ts2.11.0-all
    restart: unless-stopped
    # https://github.com/timescale/timescaledb-docker-ha/issues/359
    user: "root"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres-password"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    volumes:
      - ./timescale-data:/var/lib/postgresql/data
    secrets:
      - postgres-password
    networks:
      postgres-net:
        aliases:
          - postgres
          - postgresql
          - timescale
          - timescaledb
          - database

secrets:
  postgres-password:
    file: ./secrets/.postgres-password

networks:
  postgres-net:
    name: postgres-network