# Original file from https://github.com/orhun/git-cliff
name: Docker Automated Builds

on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            stefa168/growatt_server
            ghcr.io/${{ github.repository_owner }}/growatt_server
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      # https://github.com/docker/build-push-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          sbom: true
          provenance: true
          labels: ${{ steps.meta.outputs.labels }}
          # https://docs.docker.com/build/ci/github-actions/cache/
          cache-from: type=registry,ref=stefa168/growatt_server:buildcache
          cache-to: type=registry,ref=stefa168/growatt_server:buildcache,mode=max
#          # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
#          cache-from: type=gha
#          cache-to: type=gha,mode=max


      - name: Scan the image
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository_owner }}/growatt_server

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}